theme: jekyll-theme-leap-day
title: Vir's blog â€” go fast with readable code!
description: there's too much unused parallelism on a single core
author: Matthias Kretz
paginate: 5
markdown: kramdown

kramdown:
    input: GFM
